### PR TITLE
#8: export data of explorations to csv

### PR DESCRIPTION
**Pull request by rombautt**
Extension to the Jenkins plugin, where you can optionally configure a path where exported data sets need to be moved to.
If not configured, nothing will be moved.

Data sets are exported into a csv file if the @Exploration has export = true.

### CODE REVIEW

**Comment by jgheerardyn** [comment]
Could you check out branch 61?

We now have an additional field in the Explorer that maps a Functional<T> result to an object called Stats. Would it be possible to include in the csv:
1. the double values corresponding to Stats.getNames
2. the PropertyVerification per property as included in the Explorer

**Comment by rombautt** [comment]
Added.

You prefer to prefix the header fields? like var_z, prop_EQ 0.00, stat_average?

Sample output (case without stats):

"z","EQ 0.000000"
"0.5488135008937807","Property holds"
"0.7151893652121089","Property holds"
"0.6027633824638368","Property holds"
"0.5448831893094142","Property holds"
"0.42365480398481625","Property holds"
"0.6458941159305229","Property holds"
"0.43758720602891743","Property holds"
"0.8917730012046243","Property holds"
"0.963662762532477","Property holds"

**Comment by jgheerardyn** [comment]
Sample output is fine except that I would prefer a boolean rather than Property holds.

**Comment by rombautt** [comment]
Obsolete, pulled in #61.

**Pull request closed without merging**
