### PR TITLE
#93_finance: remove export flag

### PR DESCRIPTION
**Pull request by rombautt**

### CODE REVIEW

**Comment by jgheerardyn** [comment]
so - if the export flag is removed, does that mean that all test results are always saved in Redis?

Also - the ExplorerJSONExporter is not removed; why?

**Comment by rombautt** [comment]
Yes, that's correct, no more filter.

This also means that tests without a group will all be reported under 'no_group'.

The ExplorerJSONExporter is still there as this is the intermediate format used by the Jenkins plugin: store in json, then as a post-build step read this json and send to testpad.

**Comment by jgheerardyn** [comment]
OK - in that case, what happens if you simply run a test in IntelliJ while developing? In that case it would not have to be saved down (as it would pollute the datasets).

**Comment by rombautt** [comment]
It would write the json to a temp folder anyway.
There's no different for a test being run in Jenkins or locally.

Should I re-add it?

**Comment by jgheerardyn** [comment]
no that is fine - just wanted to understand the logic better.

**Pull request merged**
